"""Generate a deterministic sample DerivationCert for KIRO MCP testing.

Produces a fully-populated, valid, signed cert at
``agentlevy/mcp_server/sample_cert.json`` that the AgentLevy MCP server
in KIRO can verify end-to-end. Uses fixed seeds + a fixed timestamp so
the output is bit-for-bit reproducible across machines.

Run::

    source .venv/bin/activate
    python scripts/make_sample_cert.py

Then in KIRO::

    Use audit_cert_chain on the cert in agentlevy/mcp_server/sample_cert.json.
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from agentlevy.primitives.cert import DerivationCert
from agentlevy.primitives.signing import Keypair, public_key_hex


# Deterministic auditor keypair (FIXED seed for reproducibility — DO NOT
# use this in production; this is a fixture for testing the MCP server).
SANCTIONS_AGENT_SEED = bytes.fromhex(
    "abababababababababababababababababababababababababababababababab"
)
FIXED_TIMESTAMP = datetime(2026, 5, 5, 12, 0, 0, tzinfo=timezone.utc)
FIXED_CERT_ID = "11111111-2222-3333-4444-555555555555"


def main() -> None:
    sanctions_kp = Keypair.from_seed(SANCTIONS_AGENT_SEED)

    cert = DerivationCert(
        cert_id=FIXED_CERT_ID,
        task_spec_address="sha256:" + ("9" * 64),
        input_addresses=[
            "sha256:" + ("a" * 64),  # disclosure
            "sha256:" + ("b" * 64),  # sanctions list
        ],
        output_address="sha256:" + ("c" * 64),  # screen result
        operation_description={
            "operation": "kyc.sanctions_screen",
            "inputs_described": ["beneficial-owner names", "synthetic OFAC list"],
            "outputs_described": ["per-name screening result"],
        },
        subcontract_cert_addresses=[],
        seller_pubkey=public_key_hex(sanctions_kp),
        timestamp=FIXED_TIMESTAMP,
    )
    cert.sign(sanctions_kp)

    # Verify it's valid before writing
    assert cert.verify_signature(), "self-test failed: signature should verify"
    address = cert.content_address()

    # Build the full sample JSON file with KIRO testing notes
    output = {
        "_comment": (
            "Deterministic sample DerivationCert for KIRO MCP testing. "
            "Generated by scripts/make_sample_cert.py — re-run that script "
            "to regenerate. Bit-for-bit reproducible."
        ),
        "_expected_content_address": address,
        "_kiro_test_prompts": [
            "Use the agentlevy MCP server's verify_cert tool to validate "
            f"this cert at content address {address}.",
            "Use audit_cert_chain on this cert and report whether the "
            "signature is valid and the content address matches.",
        ],
        **cert.model_dump(mode="json"),
    }

    out_path = ROOT / "agentlevy" / "mcp_server" / "sample_cert.json"
    out_path.write_text(json.dumps(output, indent=2) + "\n")

    print(f"✓ wrote {out_path.relative_to(ROOT)}")
    print(f"  content_address: {address}")
    print(f"  signer pubkey:   {public_key_hex(sanctions_kp)}")
    print(f"  signature valid: {cert.verify_signature()}")
    print()
    print("Test in KIRO:")
    print(f"  Use audit_cert_chain on the cert in {out_path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
